openapi: 3.0.3
info:
  title: Official Magic Items Admin API
  description: Admin-only endpoints for managing official magic items
  version: 1.0.0

paths:
  /api/official/magic-items/{id}:
    put:
      summary: Update an official magic item
      description: |
        Allows administrators to update official Shadowdark magic items.
        Requires admin privileges (user_profiles.is_admin = true).
      operationId: updateOfficialMagicItem
      tags:
        - Admin
        - Magic Items
      security:
        - supabaseAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: UUID of the magic item to update
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MagicItemUpdate'
      responses:
        '200':
          description: Magic item updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MagicItem'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Not authorized (not admin)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Magic item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    supabaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Supabase authentication token

  schemas:
    MagicItemUpdate:
      type: object
      description: Fields that can be updated on a magic item
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Display name of the magic item
          example: "Sword of Flame +1"
        description:
          type: string
          minLength: 1
          maxLength: 5000
          description: Full description of the magic item
          example: "A longsword wreathed in magical flames..."
        traits:
          type: array
          items:
            $ref: '#/components/schemas/Trait'
          description: Array of trait objects
      additionalProperties: false

    Trait:
      type: object
      required:
        - type
        - description
      properties:
        type:
          type: string
          enum:
            - Benefit
            - Curse
            - Bonus
            - Personality
          description: Category of the trait
        description:
          type: string
          minLength: 1
          description: Description of the trait effect
          example: "Deals +1d6 fire damage on hit"

    MagicItem:
      type: object
      required:
        - id
        - name
        - slug
        - description
        - traits
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        description:
          type: string
        traits:
          type: array
          items:
            $ref: '#/components/schemas/Trait'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "Not authorized"

    ValidationError:
      type: object
      required:
        - error
        - details
      properties:
        error:
          type: string
          example: "Validation error"
        details:
          type: array
          items:
            type: object
            properties:
              path:
                type: array
                items:
                  type: string
              message:
                type: string
