openapi: 3.0.3
info:
  title: Central Search API
  version: 1.0.0
  description: Unified search across monsters, magic items, and equipment

paths:
  /api/search:
    get:
      summary: Search all content types
      description: Fuzzy search across monsters, magic items, and equipment with filtering
      operationId: searchContent
      parameters:
        - name: q
          in: query
          required: true
          description: Search query (minimum 3 characters)
          schema:
            type: string
            minLength: 3
        - name: source
          in: query
          required: false
          description: Filter by content source
          schema:
            type: string
            enum: [all, core, user]
            default: all
        - name: includeMonsters
          in: query
          required: false
          description: Include monsters in results
          schema:
            type: boolean
            default: true
        - name: includeMagicItems
          in: query
          required: false
          description: Include magic items in results
          schema:
            type: boolean
            default: true
        - name: includeEquipment
          in: query
          required: false
          description: Include equipment in results
          schema:
            type: boolean
            default: true
        - name: limit
          in: query
          required: false
          description: Maximum results to return
          schema:
            type: integer
            enum: [25, 50, 100]
            default: 25
      responses:
        "200":
          description: Successful search
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"
        "400":
          description: Invalid request (e.g., query too short)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    SearchResult:
      type: object
      required:
        - id
        - name
        - type
        - source
        - detailUrl
        - relevance
      properties:
        id:
          type: string
          description: UUID or slug identifier
        name:
          type: string
          description: Display name
        type:
          type: string
          enum: [monster, magic_item, equipment]
        source:
          type: string
          enum: [official, user]
        detailUrl:
          type: string
          description: Path to detail page
        relevance:
          type: number
          format: float
          description: Match relevance score (0-1)
        description:
          type: string
          nullable: true
          description: Brief description (optional)

    SearchResponse:
      type: object
      required:
        - results
        - total
        - query
        - filters
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/SearchResult"
        total:
          type: integer
          description: Total matching results
        query:
          type: string
          description: Echo of search query
        filters:
          type: object
          properties:
            source:
              type: string
            includeMonsters:
              type: boolean
            includeMagicItems:
              type: boolean
            includeEquipment:
              type: boolean
            limit:
              type: integer

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
        details:
          type: array
          items:
            type: object
          description: Validation error details (for 400 errors)
