openapi: 3.0.3
info:
  title: User Equipment API
  version: 1.0.0
  description: CRUD operations for user-created equipment items

paths:
  /api/user/equipment:
    get:
      summary: List user's equipment
      operationId: listUserEquipment
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: q
          in: query
          description: Search query
          schema:
            type: string
            maxLength: 200
      responses:
        '200':
          description: Paginated list of user equipment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EquipmentListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

    post:
      summary: Create new equipment
      operationId: createUserEquipment
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EquipmentCreateInput'
      responses:
        '201':
          description: Equipment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEquipment'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/user/equipment/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get equipment by ID
      operationId: getUserEquipment
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Equipment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEquipment'
        '400':
          description: Invalid ID format
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Access denied
        '404':
          description: Not found
        '500':
          $ref: '#/components/responses/InternalError'

    put:
      summary: Update equipment
      operationId: updateUserEquipment
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EquipmentUpdateInput'
      responses:
        '200':
          description: Equipment updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEquipment'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Access denied
        '404':
          description: Not found
        '500':
          $ref: '#/components/responses/InternalError'

    delete:
      summary: Delete equipment
      operationId: deleteUserEquipment
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Equipment deleted
        '400':
          description: Invalid ID format
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Access denied
        '404':
          description: Not found
        '500':
          $ref: '#/components/responses/InternalError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    Cost:
      type: object
      required:
        - amount
        - currency
      properties:
        amount:
          type: number
          minimum: 0
        currency:
          type: string
          enum: [gp, sp, cp]

    EquipmentCreateInput:
      type: object
      required:
        - name
        - item_type
        - cost
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 2000
        item_type:
          type: string
          enum: [armor, weapon, gear]
        cost:
          $ref: '#/components/schemas/Cost'
        attack_type:
          type: string
          maxLength: 50
        range:
          type: string
          maxLength: 100
        damage:
          type: string
          maxLength: 100
        armor:
          type: string
          maxLength: 50
        properties:
          type: array
          items:
            type: string
            maxLength: 50
          default: []
        slot:
          type: integer
          minimum: 0
          maximum: 10
          default: 1
        quantity:
          type: string
          maxLength: 50
        is_public:
          type: boolean
          default: false

    EquipmentUpdateInput:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 2000
        item_type:
          type: string
          enum: [armor, weapon, gear]
        cost:
          $ref: '#/components/schemas/Cost'
        attack_type:
          type: string
          maxLength: 50
        range:
          type: string
          maxLength: 100
        damage:
          type: string
          maxLength: 100
        armor:
          type: string
          maxLength: 50
        properties:
          type: array
          items:
            type: string
            maxLength: 50
        slot:
          type: integer
          minimum: 0
          maximum: 10
        quantity:
          type: string
          maxLength: 50
        is_public:
          type: boolean

    UserEquipment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        description:
          type: string
          nullable: true
        item_type:
          type: string
        cost:
          $ref: '#/components/schemas/Cost'
        attack_type:
          type: string
          nullable: true
        range:
          type: string
          nullable: true
        damage:
          type: string
          nullable: true
        armor:
          type: string
          nullable: true
        properties:
          type: array
          items:
            type: string
        slot:
          type: integer
        quantity:
          type: string
          nullable: true
        is_public:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        totalPages:
          type: integer

    EquipmentListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/UserEquipment'
        pagination:
          $ref: '#/components/schemas/Pagination'

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Authentication required

    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: array
                items:
                  type: object

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Internal server error
