-- Add Witch class spells to official_spells table
-- Source: Shadowdark Core Rules

-- Add witch to Alter Self
UPDATE public.official_spells
SET classes = classes || '["witch"]'::jsonb
WHERE slug = 'alter_self' AND NOT (classes @> '["witch"]'::jsonb);

-- Add witch to Augury
UPDATE public.official_spells
SET classes = classes || '["witch"]'::jsonb
WHERE slug = 'augury' AND NOT (classes @> '["witch"]'::jsonb);

-- Add witch to Charm Person
UPDATE public.official_spells
SET classes = classes || '["witch"]'::jsonb
WHERE slug = 'charm_person' AND NOT (classes @> '["witch"]'::jsonb);

INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Anathema', 'anathema', 'All allies revile and abandon the creature you touch for 1 day. Each time you or your allies harm the target, its former allies may pass a DC 15 Wisdom check to end the effects of the spell.', '["witch"]'::jsonb, 'Instant', 'Close', 5, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Beguile', 'beguile', 'You conjure a convincing visible and audible illusion within range. Creatures who perceive the illusion react to it as though it were real, although it can''t cause actual harm. Touching the illusion instantly reveals its false nature. You may force a creature who interacts with the illusion to make a DC 15 Wisdom check. If the creature fails, it is enchanted by the illusion for the spell''s duration and seeks to protect it.', '["witch"]'::jsonb, 'Focus', 'Near', 4, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Bogboil', 'bogboil', 'You turn a near-sized cube of ground within range into a muddy, boiling bog of quicksand. A creature stuck in the bog can''t move and must succeed on a Dexterity check vs. your spellcasting check to free itself.', '["witch"]'::jsonb, '5 round', 'Far', 2, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Broomstick', 'broomstick', 'You conjure a flying broomstick in your hand. The broomstick''s rider can fly a near distance each round and can hover in place.', '["witch"]'::jsonb, 'Focus', 'Self', 3, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Cacklerot', 'cacklerot', 'One target you touch of LV 4 or less collapses helplessly with disturbing, pained laughter for the spell''s duration.', '["witch"]'::jsonb, 'Focus', 'Close', 2, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Cat''s Eye', 'cat_s_eye', 'Your irises grow to fill your eyes and your pupils turn into black, vertical slits. You can see invisible creatures and secret doors for the spell''s duration.', '["witch"]'::jsonb, 'Focus', 'Self', 2, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Cauldron', 'cauldron', 'You conjure a bubbling cauldron next to you. It can produce one of the following effects: • Any broken mundane item placed inside the cauldron is repaired. • A fat, croaking toad leaps out and follows your instructions for the next 3 rounds. • You can place up to 3 item slots of items inside the cauldron. The cauldron expels these items the next time you cast this spell (expelling items counts as the cauldron''s single effect).', '["witch"]'::jsonb, '1 round', 'Close', 1, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Cloak Of Night', 'cloak_of_night', 'Your wrap yourself in a swirling cloak of shadows. For the spell''s duration, your armor class becomes 17 (20 on a critical spellcasting check). You have advantage on Dexterity checks to sneak and hide for the spell''s duration.', '["witch"]'::jsonb, '8 rounds', 'Self', 4, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Coven', 'coven', 'You call upon the magic you share with your fellow witches. You regain the use of one tier 3 spell or lower that you can no longer cast for the day. After successfully casting this spell, you can''t do so again until you complete a rest.', '["witch"]'::jsonb, 'Instant', 'Self', 3, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Curse', 'curse', 'A creature you touch is afflicted by one of the following curses: • Hideous boils and warts • All food tastes of ash • Voice becomes shrill • Disturbing nightmares • Always lose at gambling • An ally turns into an enemy • Fear of something ordinary', '["witch"]'::jsonb, 'Permanent', 'Close', 4, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Dimension Door', 'dimension_door', 'You teleport yourself and up to one other willing creature within close to any point you can see.', '["witch"]'::jsonb, 'Instant', 'Self', 4, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Divination', 'divination', 'You throw the divining bones or peer into the blackness between the stars, seeking a portent. You can ask the GM one yes or no question. The GM truthfully answers ''yes'' or ''no.'' If you cast this spell more than once in 24 hours, treat a failed spellcasting check for it as a critical failure instead.', '["witch"]'::jsonb, 'Instant', 'Self', 3, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Dreamwalk', 'dreamwalk', 'You and any willing creatures you choose within close range step into the dream of a sleeping creature you name that is on your same plane. You and anyone traveling with you can step out of the creature, appearing next to it as if having teleported there.', '["witch"]'::jsonb, 'Instant', 'Close', 5, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Enfeeble', 'enfeeble', 'A creature you touch has a random stat reduced to 3 (-4) for one week. Roll a do to determine which stat: 1. Strength, 2. Dexterity, 3. Constitution, 4. Intelligence, 5. Wisdom, 6. Charisma. If you fail the spellcasting check, you have a random stat reduced to 3 for a week instead.', '["witch"]'::jsonb, 'Instant', 'Close', 5, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Eyebite', 'eyebite', 'One creature you target takes 1d4 damage, and it can''t see you until the end of its next turn.', '["witch"]'::jsonb, 'Instant', 'Near', 1, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Finger Of Death', 'finger_of_death', 'One creature you touch of LV 9 or less dies. Treat a failed spellcasting check for this spell as a critical failure, and roll the mishap with disadvantage.', '["witch"]'::jsonb, 'Instant', 'Close', 5, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Fog', 'fog', 'A thick cloud of fog blooms in a close area around you, making you hard to see. The cloud moves with you. Attacks against creatures in the cloud have disadvantage.', '["witch"]'::jsonb, 'Focus', 'Close', 1, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Frog Rain', 'frog_rain', 'A rain of indignant frogs pelts a near-sized cube around a point you can see within range. All creatures within the frog rain take 1d6 damage. Any surviving frogs hop away and disappear.', '["witch"]'::jsonb, 'Instant', 'Far', 2, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Glassbones', 'glassbones', 'A creature you touch becomes fragile. It takes double damage for the spell''s duration.', '["witch"]'::jsonb, 'Focus', 'Close', 4, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Howl', 'howl', 'All enemies within near range of you must immediately make a morale check. This spell does not affect creatures that are immune to morale checks.', '["witch"]'::jsonb, 'Instant', 'Near', 3, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Hypnotize', 'hypnotize', 'One creature of LV 3 or less that can see you is rendered stupefied. Breaking the creature''s line of sight to you allows it to make a DC 15 Charisma check. On a success, the spell ends.', '["witch"]'::jsonb, 'Focus', 'Near', 1, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Invisibility', 'invisibility', 'A creature you touch becomes invisible for the spell''s duration. The spell ends if the target attacks or casts a spell.', '["witch"]'::jsonb, '10 rounds', 'Close', 2, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Mistletoe', 'mistletoe', 'Two creatures you can see within near of you become enchanted with each other for 1d8 days. Each time one of the affected creatures takes damage, it may make a DC 15 Charisma check. On a success, the spell ends.', '["witch"]'::jsonb, '1d8 days', 'Near', 3, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Moonbeam', 'moonbeam', 'A wavering ray of silvery moonlight strikes one creature within far. It takes 3d6 damage.', '["witch"]'::jsonb, 'Instant', 'Far', 4, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Mother Of Night', 'mother_of_night', 'You beseech the Mother of Night to lend you power. Make a single wish, stating it as exactly as possible. Your wish occurs, as interpreted by the GM. If you fail this spellcasting check, the Mother of Night pulls you into The Nightfall for judgment. You can''t cast this spell again until you appease her demands.', '["witch"]'::jsonb, 'Instant', 'Self', 5, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Nightmare', 'nightmare', 'You visit the dreams of one sleeping creature, sending it heart-stopping nightmares. You can target a creature whose level is less than or equal to half your level rounded down (minimum 1). The target must be sleeping, and you must have seen it before in person. If you successfully focus on this spell for 3 rounds in a row, the creature dies of fright.', '["witch"]'::jsonb, 'Focus', 'On the same plane', 4, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Oak, Ash, Thorn', 'oak_ash_thorn', 'For the spell''s duration, faeries, demons, and devils can''t attack you. These beings also can''t possess, compel, or beguile you.', '["witch"]'::jsonb, 'Focus', 'Self', 1, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Pin Doll', 'pin_doll', 'You pin a piece of hair or flesh taken from one creature to a small, burlap doll the spell conjures. On your turn while focusing on this spell, you can push a pin into the doll. Each time you do this, the creature who the hair or flesh belonged to takes 2d6 damage. After this spell ends, the piece of hair or flesh burns to ash.', '["witch"]'::jsonb, 'Focus', 'On the same plane', 3, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Poison', 'poison', 'One worn or carried object you touch becomes toxic for the spell''s duration. Any creature in contact with the object at the start of its turn takes 1d6 damage.', '["witch"]'::jsonb, '5 rounds', 'Close', 2, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Polymorph', 'polymorph', 'You transform a creature you touch into another natural creature you choose of equal or smaller size. Any gear the target carries melds into its new form. The target gains the creature''s physical stats and features, but it retains its non-physical stats and teatures. If the target goes to 0 hit points, it reverts to its true form at half its prior hit points. You can target any willing creature with this spell, or an unwilling creature whose level is less than or equal to half your level rounded down (min. 1).', '["witch"]'::jsonb, '10 rounds', 'Close', 2, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Puppet', 'puppet', 'One humanoid creature of LV 2 or less you touch becomes ensnared by your movements. On your turn, the creature mimics all your movements. If mimicking you would cause the creature to directly harm itself or an ally, it can make a DC 15 Charisma check. On a success, it resists mimicking you.', '["witch"]'::jsonb, 'Focus', 'Close', 1, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Scrying', 'scrying', 'You look into a crystal ball or reflecting pool, calling up images of a distant place. For the spell''s duration, you can see and hear a creature or location you choose that is on the same plane. This spell is DC 18 to cast if you try to scry on a creature or location that is unfamiliar to you. Each round, creatures you view may make a Wisdom check vs. your last spellcasting check. On a success, they become aware of your magical observation.', '["witch"]'::jsonb, 'Focus', 'Self', 2, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Shadowdance', 'shadowdance', 'You spin shadowstuff into a convincing visible and audible illusion at a point within near. The illusion can be as big as a person and can move within a near range of where it appeared. The illusion can''t affect physical objects. Touching the illusion reveals its false nature.', '["witch"]'::jsonb, '3 rounds', 'Near', 1, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Shapechange', 'shapechange', 'You transform yourself and any gear you carry into another natural creature you''ve seen of level 10 or less. You assume the creature''s physical stats and features, but you retain your non-physical stats and features (including INT, WIS, and CHA). If you go to 0 HP while under the effects of this spell, you revert to your true form at 1 HP.', '["witch"]'::jsonb, 'Focus', 'Self', 5, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Soul Jar', 'soul_jar', 'You transfer the soul of one creature you touch of LV 9 or less into a vessel, such as a jar. The creature''s body becomes comatose, but it doesn''t die. If the vessel opens or breaks, the creature''s soul returns to its body. You can possess the empty body with your own spirit, taking control of it. Your body becomes comatose during this time. If the body dies while you possess it, your soul returns to your body.', '["witch"]'::jsonb, 'Permanent', 'Close', 5, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Speak With Dead', 'speak_with_dead', 'A dead body you touch answers your questions in a distant, wheezing voice. You can ask the dead body up to three yes or no questions (one at a time). The GM truthfully answers ''yes'' or ''no'' to each. If you cast this spell more than once in 24 hours, treat a failed spellcasting check for it as a critical failure instead.', '["witch"]'::jsonb, 'Instant', 'Close', 3, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Spidersilk', 'spidersilk', 'Sticky spidersilk covers your hands and feet. For the spell''s duration, you can walk on vertical surfaces as easily as if it were flat ground.', '["witch"]'::jsonb, 'Focus', 'Self', 2, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Swarm', 'swarm', 'A dense swarm of biting bats, rats, or locusts appears in a near-sized cube around a point you can see within range. All creatures that start their turn within the swarm take 2d6 damage and are blinded.', '["witch"]'::jsonb, 'Focus', 'Far', 3, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Toadstool', 'toadstool', 'You conjure a plump, speckled toadstool in your hand. It disappears at the end of your next turn. A creature that eats the toadstool regains 1d6 hit points.', '["witch"]'::jsonb, 'Instant', 'Self', 2, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Void Stare', 'void_stare', 'Your eyes turn black as you look into the dark between the stars. One creature of LV 6 or less you can see falls under your control. You decide its actions during its turn.', '["witch"]'::jsonb, 'Focus', 'Far', 3, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Whisper', 'whisper', 'You whisper into another creature''s ear, planting a false memory in its mind. You describe one brief, false memory that the target believes is true going forward. If you fail this spellcasting check, the GM chooses a short, false memory to plant in your mind instead.', '["witch"]'::jsonb, 'Instant', 'Close', 3, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Willowman', 'willowman', 'You call upon the Willowman to appear in one creature''s mind, filling it with supernatural terror. Choose one creature of LV 2 or less within range. That creature must immediately make a morale check. Even creatures that are not normally subject to morale checks (such as undead) must do so.', '["witch"]'::jsonb, 'Instant', 'Near', 1, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.official_spells (name, slug, description, classes, duration, range, tier, source, author_notes, icon_url, art_url) VALUES ('Witchlight', 'witchlight', 'You summon a floating marsh light that bobs in the air and casts light out to a close radius around it. The light can change colors and take on vague shapes. It can float up to a near distance on your turn.', '["witch"]'::jsonb, 'Focus', 'Near', 1, 'Shadowdark Core', NULL, NULL, NULL) ON CONFLICT (slug) DO NOTHING;
