/**
 * Auto-generate Shadowdark-themed encounter table names
 * Format: [Location] of [Noun]
 * Example: "Crypt of Shadows", "Temple of Dread"
 */

const LOCATIONS = [
  "Crypt",
  "Temple",
  "Tomb",
  "Caverns",
  "Ruins",
  "Tower",
  "Keep",
  "Dungeon",
  "Depths",
  "Halls",
  "Vault",
  "Sanctum",
  "Catacombs",
  "Labyrinth",
  "Warren",
  "Lair",
  "Den",
  "Grove",
  "Marsh",
  "Barrow",
  "Citadel",
  "Fortress",
  "Monastery",
  "Abbey",
  "Chapel",
  "Shrine",
  "Catacomb",
  "Ossuary",
  "Mines",
  "Pit",
  "Chasm",
  "Abyss",
  "Grotto",
  "Chamber",
  "Passages",
  "Tunnels",
  "Gates",
  "Threshold",
  "Spire",
  "Pinnacle",
  "Necropolis",
  "Mausoleum",
  "Sepulcher",
  "Charnel House",
  "Oubliette",
  "Undercroft",
  "Cairn",
  "Dolmen",
  "Crypts",
  "Cistern",
  "Cloister",
  "Reliquary",
  "Archive",
  "Repository",
  "Hollow",
  "Chantry",
  "Foundry",
  "Warrens",
  "Stronghold",
  "Redoubt",
];

const NOUNS = [
  "Shadows",
  "Dread",
  "Doom",
  "Despair",
  "Souls",
  "Dead",
  "Night",
  "Blood",
  "Bones",
  "Darkness",
  "Terror",
  "Madness",
  "Woe",
  "Peril",
  "Ruin",
  "Death",
  "Curses",
  "Screams",
  "Whispers",
  "Agony",
  "Torment",
  "Sorrow",
  "Nightmares",
  "Decay",
  "Rot",
  "Plague",
  "Ash",
  "Embers",
  "Frost",
  "Suffering",
  "Anguish",
  "Horror",
  "Chaos",
  "Oblivion",
  "Void",
  "Fangs",
  "Claws",
  "Chains",
  "Iron",
  "Stone",
  "Flame",
  "Venom",
  "Blight",
  "Wyrms",
  "Serpents",
  "Ravens",
  "Crows",
  "Vipers",
  "Vermin",
  "Spectres",
  "Wraiths",
  "Ghouls",
  "Revenants",
  "Corpses",
  "Carrion",
  "Tombs",
  "Crimson",
  "Scarlet",
  "Midnight",
  "Dusk",
  "Eclipse",
  "Winter",
  "Famine",
  "Pestilence",
  "Thorns",
  "Briars",
  "Weeping",
  "Moaning",
  "Wailing",
  "Unrest",
];

/**
 * Generate a random encounter table name
 * @returns Shadowdark-themed name in format "[Location] of [Noun]"
 */
export function generateEncounterTableName(): string {
  const location = LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)];
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)];
  return `${location} of ${noun}`;
}
